<?php
	use sistema\helpers\Html;
?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">

		<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame
		Remove this if you use the .htaccess -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title><?= isset($titulo) ? $titulo : '' ?></title>
		<meta name="description" content="Gerenciador de conteúdos desenvolvida pela Towty Tecnologia!">
		<meta name="author" content="Towty Tecnologia">

		<meta name="viewport" content="width=device-width; initial-scale=1.0">

		<!-- Replace favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
		<link rel="shortcut icon" href="/favicon.ico">
		<link rel="apple-touch-icon" href="/apple-touch-icon.png">
		
		<?php
			 //listar scripts
			 if(isset($Styles))
			 {
				foreach ($Styles as $css) 
				{ ?>					
					<link rel="stylesheet" type="text/css" href="<?= $this->diretorioFisicoIncludes . 'css/' . $css ?>" />
		<?php 	}
			 }
		?>
		
		<link rel="stylesheet" type="text/css" href="<?= $this->diretorioFisicoIncludes . 'css/jquery-easy-ui-default/easyui.css' ?>" />		
		
		<script src="<?= $this->diretorioFisicoIncludes . 'scripts/jquery-1.10.2.min.js' ?>" type="text/javascript"></script>
		<script src="<?= $this->diretorioFisicoIncludes . 'scripts/jquery.easyui.min.js' ?>" type="text/javascript"></script>
		<script src="<?= $this->diretorioFisicoIncludes . 'scripts/easyui-lang-pt_BR.js' ?>" type="text/javascript"></script>
		<script src="<?= $this->diretorioFisicoIncludes . 'scripts/jquery.maskedinput.min.js' ?>" type="text/javascript"></script>		
				
		<?php
			 //listar scripts
			 if(isset($Scripts))
			 {
				foreach ($Scripts as $script) 
				{ ?>
					<script src="<?= $this->diretorioFisicoIncludes . 'scripts/' . $script ?>" type="text/javascript"></script>
		<?php 	}
			 }
		?>
		
		<script src="<?= $this->diretorioFisicoIncludes . 'scripts/util.js' ?>" type="text/javascript"></script>
	</head>
	<body>
		<div>
			<header>
				<h1>Gecko's CMS</h1>
			</header>
			<nav>
				<p>
					<?= Html::actionlink('Home') ?>	
				</p>
				<p>
					<?= Html::actionlink('Notícias', 'noticia', '') ?>
				</p>
				<p>
					<?= Html::actionlink('Cadastrar', 'noticia', 'cadastrar') ?>
				</p>
			</nav>

			<div id="conteudo">
				<?= $conteudoView ?>
			</div>

			<footer>
				<p>
					&copy; Copyright  by Will
				</p>
			</footer>
		</div>
	</body>
</html>
